Work around for issue 389957. ant-1.8.2 is loaded by SystemClassLoader. But ant-launcher classes are loaded by Plugin ClassLoader. As a result ant -launcher Classes are not visible to ant.jar, thus java.lang.NoClassDefFoundError: org/apache/tools/ant/launch/AntMain error happens